# The LifelineSMP's managing mod's config, for the client.
# Typically, you would want to edit this in ModMenu, but if you want to just edit it here...
# Go off ig?

# The stream notification system used for the streamer.
# Accepted values: STREAMLABS, STREAMELEMENTS
type: STREAMLABS
# The API key for the stream notification system.
api-key: ""